# Generated by Django 5.2.1 on 2025-06-17 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Введите заголовок статьи (максимум 200 символов)', max_length=200, verbose_name='Заголовок')),
                ('content', models.TextField(help_text='Основной текст статьи', verbose_name='Содержимое')),
                ('preview_image', models.ImageField(blank=True, help_text='Загрузите изображение для превью статьи', null=True, upload_to='blog_previews/', verbose_name='Превью изображение')),
                ('created_date', models.DateTimeField(auto_now_add=True, help_text='Дата и время создания записи (устанавливается автоматически)', verbose_name='Дата создания')),
                ('is_published', models.BooleanField(default=False, help_text='Отметьте, чтобы статья была видна на сайте', verbose_name='Опубликовано')),
                ('views_count', models.PositiveIntegerField(default=0, help_text='Счетчик просмотров статьи (обновляется автоматически)', verbose_name='Количество просмотров')),
            ],
            options={
                'verbose_name': 'Блоговая запись',
                'verbose_name_plural': 'Блоговые записи',
                'ordering': ['-created_date'],
                'indexes': [models.Index(fields=['-created_date'], name='blog_blogpo_created_c90504_idx'), models.Index(fields=['is_published'], name='blog_blogpo_is_publ_c847aa_idx')],
            },
        ),
    ]
